services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Coffee       # ชื่อผู้ใช้
      POSTGRES_PASSWORD: 123456  # รหัสผ่าน
      POSTGRES_DB: Coffee         # ชื่อฐานข้อมูลd
    ports:
      - "5432:5432"
  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dpu.ac.th
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres


volumes:
  db:
